FROM python:3.7

RUN mkdir /opt/app
WORKDIR /opt/app

RUN pip3 install gunicorn

COPY requirements.txt .
RUN pip3 install -r requirements.txt

COPY . .

ARG SECRET_KEY
RUN sed -i "s/#SECRET_KEY#/SECRET_KEY = '${SECRET_KEY}'/" config.py

EXPOSE 8000
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "app:app"]
